Patrick Johnston  February 7, 2025


  0  Collapse this comment
Copy link
The job of a dtor is to clean up resources, I don’t think it’s surprising that it fails at the job of modifying some in flight variable that has nothing to do with the object being destroyed





LB  February 3, 2025


  0  Collapse this comment
Copy link
Ouch, so I guess C++ doesn’t have any way to let destructors attach info to an in-flight exception, you always have to wrap code in a try block outside the destructor? I actually didn’t know that, how unfortunate. I suppose the next best thing is wrapping everything in a lambda that is called by a helper function that wraps the lambda call in a try block so it can attach info in one or more of the catch clauses or rethrow it as a nested exception.