Neil Rashbrook  October 22, 2022
Â· Edited

  1  Collapse this comment
Copy link
As I understand it, the C++ destructors will always execute at the end of the try block, i.e. before any catch block possibly executes (potentially as a result of an exception thrown by a destructor), which differs from a (e.g.) C#-style finally block, which does runs after any catch block.